"""Add Historico

Revision ID: e4de1ebfbf3b
Revises: 67cec0621335
Create Date: 2024-01-30 16:55:22.874357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4de1ebfbf3b'
down_revision = '67cec0621335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lanc_recibo', sa.Integer(), nullable=False),
    sa.Column('lanc_obs', sa.String(length=256), nullable=False),
    sa.Column('lanc_tipo_recbico', sa.String(length=256), nullable=False),
    sa.Column('lanc_nome_dizimista', sa.String(length=256), nullable=False),
    sa.Column('lanc_movimentacao', sa.String(length=256), nullable=False),
    sa.Column('lanc_cong', sa.String(length=256), nullable=False),
    sa.Column('lanc_data_lan', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_id'), 'historico', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historico_id'), table_name='historico')
    op.drop_table('historico')
    # ### end Alembic commands ###