"""Update Lancamento

Revision ID: ebc48123e636
Revises: 6170e89178fe
Create Date: 2024-02-01 05:37:42.419121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc48123e636'
down_revision = '6170e89178fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lancamento', 'data_lan')
    op.drop_column('lancamento', 'inflow')
    op.drop_column('lancamento', 'outflow')
    op.drop_column('lancamento', 'num_doc')
    op.drop_column('lancamento', 'cong')
    op.drop_column('lancamento', 'recibo')
    op.drop_column('lancamento', 'suplier')
    op.drop_column('lancamento', 'history')
    op.drop_column('lancamento', 'data_ven')
    op.drop_column('lancamento', 'tither')
    op.drop_column('lancamento', 'status')
    op.drop_column('lancamento', 'tipo_doc')
    op.drop_column('lancamento', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lancamento', sa.Column('value', sa.VARCHAR(length=256), nullable=False))
    op.add_column('lancamento', sa.Column('tipo_doc', sa.VARCHAR(length=256), nullable=False))
    op.add_column('lancamento', sa.Column('status', sa.VARCHAR(length=256), nullable=False))
    op.add_column('lancamento', sa.Column('tither', sa.VARCHAR(length=256), nullable=False))
    op.add_column('lancamento', sa.Column('data_ven', sa.DATE(), nullable=False))
    op.add_column('lancamento', sa.Column('history', sa.VARCHAR(length=256), nullable=False))
    op.add_column('lancamento', sa.Column('suplier', sa.VARCHAR(length=256), nullable=False))
    op.add_column('lancamento', sa.Column('recibo', sa.VARCHAR(length=256), nullable=False))
    op.add_column('lancamento', sa.Column('cong', sa.VARCHAR(length=256), nullable=False))
    op.add_column('lancamento', sa.Column('num_doc', sa.VARCHAR(length=256), nullable=False))
    op.add_column('lancamento', sa.Column('outflow', sa.VARCHAR(length=256), nullable=False))
    op.add_column('lancamento', sa.Column('inflow', sa.VARCHAR(length=256), nullable=False))
    op.add_column('lancamento', sa.Column('data_lan', sa.DATE(), nullable=False))
    # ### end Alembic commands ###